### PR TITLE
Wikey typo and readability

### PR DESCRIPTION
**Pull request by wikey**
I did a pass through most of the documentation I have read for some minor readability polish. 

The biggest additions are in the getting started FTP tutorial where I added a link to the FTP-specific documentation and a note that SFTP will only work with the default cPanel user, not an FTP-specific user, which I learned from the FTP documentation page.

### CODE REVIEW

**Comment by timmmmyboy** [comment]
You've been busy! Thanks again for going over all this!

**Comment by wikey** [comment]
Happy to help! I'm putting together a short course on personal website building using Reclaim for some graduate students I work with so I might have some more time to add things as I continue plotting out the material. Have you considered, or would you be interested in, a page on setting up SSL through cPanel and what that accomplishes?

**Comment by timmmmyboy** [comment]
That's awesome! I've definitely considered an SSL tutorial. Thing is I've also been holding off in hopes that we'll have a better way of integrating [Let's Encrypt](https://letsencrypt.org/) directly into cPanel in the near future. We're doing it for folks manually right now and I'd love to have a way to just offer free SSL rather than encouraging folks to pay for a cert via the traditional process.

**Comment by wikey** [comment]
That _would_ be great. It seems like integration should be possible along the lines of the Apache module they packaged up for Debian though, from their various support forums, it looks like the automatic client tools have trouble with python 2.6. What does the manual process require?

**Comment by timmmmyboy** [comment]
We've been using the guide at https://forums.cpanel.net/threads/how-to-installing-ssl-from-lets-encrypt.513621/ that cPanel put together which does support Python 2.6, but it requires root access to provision and install the certs so we handle it by support request for those who ask for it. I assume (hope?) cPanel will be working on a user-facing interface to do the same thing in the future that could be built right in (even better would be firing it off by default when a domain is added to Apache so all domains would support SSL by default, not sure if that's just dreaming though).

**Comment by wikey** [comment]
Well they have marked the related feature request as "Planned" and the comment thread is full of one user advertising his commercial plugin, so it sounds like integration is indeed possible. In the meantime, I'm going to draft a post on the existing method to create and install a self-signed SSL cert so OwnCloud will stop telling me how vulnerable I am to MITM attacks. You are welcome to whatever I get together, in case it turns out to be useful.

**Pull request merged**
